# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'student_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 800)
        MainWindow.setMinimumSize(QtCore.QSize(800, 800))
        MainWindow.setMaximumSize(QtCore.QSize(800, 800))
        MainWindow.setStyleSheet("background-color:#808080")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.student_number = QtWidgets.QLineEdit(self.centralwidget)
        self.student_number.setGeometry(QtCore.QRect(300, 230, 200, 30))
        self.student_number.setMinimumSize(QtCore.QSize(200, 30))
        self.student_number.setMaximumSize(QtCore.QSize(200, 30))
        self.student_number.setStyleSheet("background-color:#ffffff")
        self.student_number.setAlignment(QtCore.Qt.AlignCenter)
        self.student_number.setObjectName("student_number")
        self.student_password = QtWidgets.QLineEdit(self.centralwidget)
        self.student_password.setGeometry(QtCore.QRect(300, 310, 200, 30))
        self.student_password.setMinimumSize(QtCore.QSize(200, 30))
        self.student_password.setMaximumSize(QtCore.QSize(200, 30))
        self.student_password.setStyleSheet("background-color:#ffffff")
        self.student_password.setAlignment(QtCore.Qt.AlignCenter)
        self.student_password.setObjectName("student_password")
        self.student_login = QtWidgets.QPushButton(self.centralwidget)
        self.student_login.setGeometry(QtCore.QRect(350, 410, 100, 30))
        self.student_login.setMinimumSize(QtCore.QSize(100, 30))
        self.student_login.setMaximumSize(QtCore.QSize(100, 30))
        self.student_login.setStyleSheet("background-color:#ffffff")
        self.student_login.setObjectName("student_login")
        self.student_login_back = QtWidgets.QPushButton(self.centralwidget)
        self.student_login_back.setGeometry(QtCore.QRect(40, 710, 50, 30))
        self.student_login_back.setMinimumSize(QtCore.QSize(50, 30))
        self.student_login_back.setMaximumSize(QtCore.QSize(50, 30))
        self.student_login_back.setStyleSheet("background-color:#ffffff")
        self.student_login_back.setObjectName("student_login_back")
        self.student_forgot = QtWidgets.QPushButton(self.centralwidget)
        self.student_forgot.setGeometry(QtCore.QRect(640, 710, 120, 30))
        self.student_forgot.setMinimumSize(QtCore.QSize(120, 30))
        self.student_forgot.setMaximumSize(QtCore.QSize(100, 30))
        self.student_forgot.setStyleSheet("background-color:#ffffff")
        self.student_forgot.setObjectName("student_forgot")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.student_number.setPlaceholderText(_translate("MainWindow", "student number"))
        self.student_password.setPlaceholderText(_translate("MainWindow", "password"))
        self.student_login.setText(_translate("MainWindow", "Login"))
        self.student_login_back.setText(_translate("MainWindow", "Back"))
        self.student_forgot.setText(_translate("MainWindow", "Forgot Password?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
