# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'student_forgot.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 800)
        MainWindow.setMinimumSize(QtCore.QSize(800, 800))
        MainWindow.setMaximumSize(QtCore.QSize(800, 800))
        MainWindow.setStyleSheet("background-color: #808080")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_lastname_teacher = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_lastname_teacher.setGeometry(QtCore.QRect(180, 160, 551, 22))
        self.lineEdit_lastname_teacher.setStyleSheet("background-color:#ffffff")
        self.lineEdit_lastname_teacher.setText("")
        self.lineEdit_lastname_teacher.setObjectName("lineEdit_lastname_teacher")
        self.pushButton_Lesson_Edit_edit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Lesson_Edit_edit.setGeometry(QtCore.QRect(330, 270, 181, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_Lesson_Edit_edit.setFont(font)
        self.pushButton_Lesson_Edit_edit.setStyleSheet("background-color: #ffffff")
        self.pushButton_Lesson_Edit_edit.setObjectName("pushButton_Lesson_Edit_edit")
        self.label_last_name_teacher = QtWidgets.QLabel(self.centralwidget)
        self.label_last_name_teacher.setGeometry(QtCore.QRect(70, 160, 100, 20))
        self.label_last_name_teacher.setStyleSheet("background-color: #ffffff")
        self.label_last_name_teacher.setObjectName("label_last_name_teacher")
        self.lineEdit_username_teacher = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_username_teacher.setGeometry(QtCore.QRect(180, 210, 551, 22))
        self.lineEdit_username_teacher.setStyleSheet("background-color: #ffffff")
        self.lineEdit_username_teacher.setText("")
        self.lineEdit_username_teacher.setObjectName("lineEdit_username_teacher")
        self.lineEdit_first_name_teacher = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_first_name_teacher.setGeometry(QtCore.QRect(180, 110, 551, 22))
        self.lineEdit_first_name_teacher.setStyleSheet("background-color:#ffffff\n"
"")
        self.lineEdit_first_name_teacher.setText("")
        self.lineEdit_first_name_teacher.setObjectName("lineEdit_first_name_teacher")
        self.label_first_name_teacher = QtWidgets.QLabel(self.centralwidget)
        self.label_first_name_teacher.setGeometry(QtCore.QRect(70, 110, 100, 20))
        self.label_first_name_teacher.setStyleSheet("background-color: #ffffff")
        self.label_first_name_teacher.setObjectName("label_first_name_teacher")
        self.label_username_teacher = QtWidgets.QLabel(self.centralwidget)
        self.label_username_teacher.setGeometry(QtCore.QRect(70, 210, 100, 20))
        self.label_username_teacher.setStyleSheet("background-color: #ffffff")
        self.label_username_teacher.setObjectName("label_username_teacher")
        self.label_username_teacher_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_username_teacher_2.setGeometry(QtCore.QRect(80, 380, 100, 20))
        self.label_username_teacher_2.setStyleSheet("background-color: #ffffff")
        self.label_username_teacher_2.setObjectName("label_username_teacher_2")
        self.lineEdit_username_teacher_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_username_teacher_2.setGeometry(QtCore.QRect(190, 380, 551, 22))
        self.lineEdit_username_teacher_2.setStyleSheet("background-color: #ffffff")
        self.lineEdit_username_teacher_2.setText("")
        self.lineEdit_username_teacher_2.setObjectName("lineEdit_username_teacher_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_Lesson_Edit_edit.setText(_translate("MainWindow", "Search"))
        self.label_last_name_teacher.setText(_translate("MainWindow", "Last Name:"))
        self.label_first_name_teacher.setText(_translate("MainWindow", "First Name:"))
        self.label_username_teacher.setText(_translate("MainWindow", "Student Number:"))
        self.label_username_teacher_2.setText(_translate("MainWindow", "Password:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
