# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'teacher_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 800)
        MainWindow.setMinimumSize(QtCore.QSize(800, 800))
        MainWindow.setMaximumSize(QtCore.QSize(800, 800))
        MainWindow.setStyleSheet("background-color:#808080\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.username = QtWidgets.QLineEdit(self.centralwidget)
        self.username.setGeometry(QtCore.QRect(300, 230, 200, 30))
        self.username.setMinimumSize(QtCore.QSize(200, 30))
        self.username.setMaximumSize(QtCore.QSize(200, 30))
        self.username.setStyleSheet("background-color:#ffffff")
        self.username.setAlignment(QtCore.Qt.AlignCenter)
        self.username.setObjectName("username")
        self.teacher_password = QtWidgets.QLineEdit(self.centralwidget)
        self.teacher_password.setGeometry(QtCore.QRect(300, 310, 200, 30))
        self.teacher_password.setMinimumSize(QtCore.QSize(200, 30))
        self.teacher_password.setMaximumSize(QtCore.QSize(200, 30))
        self.teacher_password.setStyleSheet("background-color:#ffffff")
        self.teacher_password.setAlignment(QtCore.Qt.AlignCenter)
        self.teacher_password.setObjectName("teacher_password")
        self.teacher_login = QtWidgets.QPushButton(self.centralwidget)
        self.teacher_login.setGeometry(QtCore.QRect(350, 410, 100, 30))
        self.teacher_login.setMinimumSize(QtCore.QSize(100, 30))
        self.teacher_login.setMaximumSize(QtCore.QSize(100, 30))
        self.teacher_login.setStyleSheet("background-color:#ffffff")
        self.teacher_login.setObjectName("teacher_login")
        self.teacher_login_back = QtWidgets.QPushButton(self.centralwidget)
        self.teacher_login_back.setGeometry(QtCore.QRect(40, 710, 50, 30))
        self.teacher_login_back.setMinimumSize(QtCore.QSize(50, 30))
        self.teacher_login_back.setMaximumSize(QtCore.QSize(50, 30))
        self.teacher_login_back.setStyleSheet("background-color:#ffffff")
        self.teacher_login_back.setObjectName("teacher_login_back")
        self.labelResult = QtWidgets.QLabel(self.centralwidget)
        self.labelResult.setGeometry(QtCore.QRect(200, 510, 400, 20))
        self.labelResult.setStyleSheet("background-color:#808080")
        self.labelResult.setText("")
        self.labelResult.setAlignment(QtCore.Qt.AlignCenter)
        self.labelResult.setObjectName("labelResult")
        self.teacher_forgot = QtWidgets.QPushButton(self.centralwidget)
        self.teacher_forgot.setGeometry(QtCore.QRect(640, 710, 120, 30))
        self.teacher_forgot.setMinimumSize(QtCore.QSize(120, 30))
        self.teacher_forgot.setMaximumSize(QtCore.QSize(100, 30))
        self.teacher_forgot.setStyleSheet("background-color:#ffffff")
        self.teacher_forgot.setObjectName("teacher_forgot")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.username.setPlaceholderText(_translate("MainWindow", "username"))
        self.teacher_password.setPlaceholderText(_translate("MainWindow", "password"))
        self.teacher_login.setText(_translate("MainWindow", "Login"))
        self.teacher_login_back.setText(_translate("MainWindow", "Back"))
        self.teacher_forgot.setText(_translate("MainWindow", "Forgot Password?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
